server:
  port: 8090
  compression:
    enabled: true
  error:
    whitelabel:
        enabled: false
spring:
  output:
    ansi:
      enabled: detect
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/halo3
    username: root
    password: test123
  sql:
    init:
      mode: always
      platform: mysql
  codec:
    max-in-memory-size: 10MB
  messages:
    basename: config.i18n.messages
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
  profiles:
    active: dev
halo:
  external-url: "https://3e51-120-196-86-13.ap.ngrok.io/"
#  external-url: "https://localhost:8090/"
  work-dir: ${user.home}/halo-dev
  plugin:
    plugins-root: ${halo.work-dir}/plugins
  attachment:
    resource-mappings:
      - pathPattern: /upload/**
        locations:
          - migrate-from-1.x

springdoc:
  api-docs:
    enabled: false

logging:
  file:
    name: ${halo.work-dir}/logs/halo.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 0

management:
  endpoints:
    web:
      exposure:
          include: ["health", "info", "startup", "globalinfo"]
  endpoint:
    health:
      probes:
        enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
